name: Update Notebook

on: push

jobs:
  with-papermill:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          repository: 'casca/covid19-notebook'
          ref: master
          persist-credentials: true
      - name: action
        uses: casca/papermill-docker-action@master
        with:
          notebook: charts.ipynb
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: 'casca/covid19-notebook'
          github_token: ${{ secrets.GITHUB_TOKEN }}
